project:
  type: book
  output-dir: docs

book:
  title: "Microeconometrics: Methods and Applications"
  author: "Damian Clarke"
  page-navigation: true
  repo-url: https://github.com/damiancclarke
  downloads: [pdf, epub]
  chapters:
    - part: index.qmd
      chapters: 
        - 00_01_About.qmd
        - 00_02_Download.qmd
    - part: 01_00_FollowingR.qmd
      chapters: 
        - 01_01_IntroductionR.qmd
        - 01_02_Chapter2R.qmd
        - 01_03_Chapter3R.qmd
        - 01_04_Chapter4R.qmd
    - part: 02_00_FollowingStata.qmd
      chapters: 
        - 02_01_IntroductionStata.qmd
        - 02_02_Chapter2Stata.qmd
        - 02_03_Chapter3Stata.qmd
    - part: 03_00_FollowingPython.qmd
      chapters:
        - 03_01_IntroductionPython.qmd
        - 03_02_Chapter2Python.qmd
        - 03_03_Chapter3Python.qmd
    - 06_references.qmd
    
bibliography: references.bib

format:
  html:
    theme: pulse
    number-sections: false

editor: visual